### ISSUE TITLE
Adapter production

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/Amiga-Digital-Video#13]
I set up this thread to keep anyone informed who wants to buy an assembled adapter from me.
My first builds are nearly sold out (all ECS are gone or reserved) and I am in the process of ordering more parts. I will keep you informed.

**Comment by culexus8** [comment]
I see you mention a V2 board in the readme. Is this for the A600?

**Comment by c0pperdragon** [comment]
I sold the last part today, but expect more material to arrive in a few days.  
From now on I will only build the V2 variant which is OCS and ECS compatible.

**Comment by c0pperdragon** [comment]
I spent parts of yesterday and today to assemble 10 Revison 2 adapters (feeling like a christmas elf all the while ;-) ) .

As it turns out, this is really labour-intensive so I need to adjust my prizing a bit (also to cover various overhead losses).
I can give out these adapters now for €29 plus shipping (€6 in Austria, €10 in Europe, €15 international, UK is currently not possible due to canceled air traffic).
Payment only via paypal to my account: reinhard.grafl@aon.at

Please reserve your adapter(s) by email and wait for my response before transfering any money.

If you cannot get any of these right now, do not worry. I will continue to make the adapters as long as there is demand.

**Comment by Centrinouk** [comment]
Hi, interested in adapter but I'm from the UK, could you update when shipping is available please? Thanks

**Comment by c0pperdragon** [comment]
My latest batch is already sold out. I expect more parts to arrive in a few days to make more adapters.

**Comment by karynroberts** [comment]
> My latest batch is already sold out. I expect more parts to arrive in a few days to make more adapters.

Hi there - great project - I would like to get two of these :) thanks.

**Comment by kipper2k** [comment]
Hi,  Is the Rev1 board same as rev2. i cannot find the gerbers for them,  are they public ?

 Thanks, very nice project

**Comment by 65Thumper** [comment]
Would like to say, great job! 
Also like to order 3 adapters, Thanks!!

**Comment by c68696c66** [comment]
@kipper2k l found the v2 adapter gerbers here: https://github.com/c0pperdragon/RGBtoHDMI/tree/master/kicad_AmigaAdapter (looks like there is a pending pull request to merge it from this fork to the main repo...)

**Comment by kipper2k** [comment]
found them. thanks for the info :)

**Comment by nyteshade** [comment]
Would love a completed unit or two. Curious if there’s any known effort to get ECS/AGA support built?

**Comment by amigacommodore** [comment]
I would like to order the adaptor but I live in Australia

**Comment by c68696c66** [comment]
@kipper2k I opened the project in KiCad and generated the BOM. U4 seems to be a LDO Voltage Regulator TLV74333PDBVR

**Comment by c0pperdragon** [comment]
Please do not clutter up this thread with off-topic stuff. Please create seperate threads for this.

**Comment by warrengc3** [comment]
Hi, Any more ECS we can order?

**Comment by 65Thumper** [comment]
Yes, I still would like 3 for my Amiga 500s,  assemble of course, thanks!
E.Cotton

Gesendet mit meinem HTC

----- Nachricht beantworten -----
Von: "George Warren" <notifications@github.com>
An: "c0pperdragon/Amiga-Digital-Video" <Amiga-Digital-Video@noreply.github.com>
Cc: "65Thumper" <edcotton@gmx.de>, "Comment" <comment@noreply.github.com>
Betreff: [c0pperdragon/Amiga-Digital-Video] Adapter production (#13)
Datum: Fr., Jan. 1, 2021 23:08

Hi, Any more ECS we can order?

&mdash;You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by c0pperdragon** [comment]
Please send me an email so I can put you on my preorder list (which is growing quite long already).

**Comment by amigacommodore** [comment]
I am yet to get a confirmation that you have put me on your list ?

**Comment by c0pperdragon** [comment]
Please do not use this thread for reservations. I intend this striktly for announcments.  Send me an e-mail instead.

**Comment by c0pperdragon** [comment]
I have finally received the PCBs I had ordered before christmas and was able to build 14 more adapters. With about 200 units on my reservation list already, this seems not much, but it is at least something. 
100 more PCBs are on their way and I am going to order more material  still..

I will contact the persons on the top of my list which are not in the UK (sorry, but there is still no mail service) and have sent send me an email before 31.12.2020.

**Comment by c0pperdragon** [comment]
Have received 100 PCBs to build adapters from. With my current workflow I will be able to build about 16 parts in two days. I will send out notifications accordingly.

**Comment by c0pperdragon** [comment]
Production is progresssing smoothly. So far I have processed all requests that were sent to me before 7.1. 20:00.
Hope to be able to catch up eventually....

**Comment by c0pperdragon** [comment]
I have completed processing all queued user request and have a few pieces left. As I don't plan to build any more of these adapters these few can still be bought directly and after that you need to find other sources.

**Comment by c0pperdragon** [comment]
During the last days I have sold off my remaining adapters. I don't plan to build any more of these in the forseeable future. As there are already other people taking up production, you may find such adapters on ebay or similiar platforms.
