### ISSUE TITLE
I need the BOM

### ISSUE THREAD

**Issue by UnaClocker** [c0pperdragon/Amiga-Digital-Video#24]
I can't seem to find the BOM for the Denise adapter board. I downloaded the gerbers, and had a set of boards made at OSHPark. Got a BOM file for those of us soldering the thing together ourselves? Maybe I'm missing it.

**Comment by Tom-PCB** [comment]
[amiga_bom.xlsx](https://github.com/c0pperdragon/Amiga-Digital-Video/files/5825610/amiga_bom.xlsx)
[amiga_cpl.xlsx](https://github.com/c0pperdragon/Amiga-Digital-Video/files/5825611/amiga_cpl.xlsx)

files are made for "JLCPCB"  to maufacture the PCB and solder the SMD parts

https://cart.jlcpcb.com/quote?orderType=1

**Comment by c68696c66** [comment]
The V2 bom is available, see https://github.com/c0pperdragon/Amiga-Digital-Video/issues/15#issuecomment-761044838 
-> https://github.com/c0pperdragon/RGBtoHDMI/blob/master/kicad_AmigaAdapter/V2/deniseadapter_bom.ods

**Comment by ryanm101** [comment]
@c0pperdragon what is the BOM for the small board? (mainly after the footprint of the resistors / caps)

**Comment by c0pperdragon** [comment]
The passives are all 0805.

**Comment by ryanm101** [comment]
thanks
