### ISSUE TITLE
A3000 Support?

### ISSUE THREAD

**Issue by nyteshade** [c0pperdragon/Amiga-Digital-Video#35]
Is the new ECS mode support working for the A3000?

**Comment by c0pperdragon** [comment]
Sorry, but no. The current solution is restricted to the 70ns / pixel timing. No super-high-res or productivity modes.

**Comment by jlavinen** [comment]
What prevents implementing 35ns pixels? Pixel clock not available? New hardware needed to do this? RP0 too slow?

**Comment by c0pperdragon** [comment]
Pixel clock could probably be created by combining both the 7Mhz and the CDAC line. This would require a new adapter at least.
But the true reason is the speed. The Pi is not fast enough to transfer this amount of data through the GPIO pins using the CPU.
It is even barely fast enough for the 70ns modes. 
Using other versions of the Pi will also not help, as having multiple cores only makes this kind of real-time processing even more difficult.
