### ISSUE TITLE
Graffiti or ColorMaster 24 mode? 

### ISSUE THREAD

**Issue by aiobofh** [c0pperdragon/Amiga-Digital-Video#46]
Would it even be technically possible to bring some "new" cool graphics modes, compatible with either Grafitti or ColorMaster 24 (or 12) to the RGB2HDMI?

Just tossing some ideas... :)

**Comment by c0pperdragon** [comment]
This issue is basically identical to:  https://github.com/c0pperdragon/Amiga-Digital-Video/issues/27

**Comment by aiobofh** [comment]
Great... Missed that one, for some reason. Thanks!
