### ISSUE TITLE
Cannot make the board work with an audio injector

### ISSUE THREAD

**Issue by ShoresOfNowhere** [c0pperdragon/Amiga-Digital-Video#49]
Hi!

The first thing is thanking you and everybody that worked on this marvelous little board granting our Amigas with the power of HDMI output! Many, many thanks!

As to the subject of this issue, in your wiki you mention the possibility of using an audio injector as to inject the analog audio signal of the Amiga in the HDMI signal. Liking the idea I bought the exact model of audio injector you link in the wiki, but I'm having problems in connecting it with the RGBtoHDMI output.

What's happening is that it seems that something in the signal produced by the RGBtoHDMI prevents the injector from doing its job: if I connect ONLY audio, I can hear the Amiga audio on the HDMI, if I connect another HDMI source (I've tried with my RPi4, for example) I can see the RPi4 video AND hear the Amiga audio, but if the Amiga RGBtoHDMI out is connected... then I only see the Amiga, but no audio!

Any advice on what should I try changing in the settings as to get it work properly?

Any indications of what do the various HDMI mode settings mean? It seems that my 4k display doesn't like any of them besides DVI compatible... What am I doing wrong?

And what CPLD do I have in my board? Would it be useful using the CPLD menu to reprogram it?

Thanks again for your hard work and for any advice you might have!

**Comment by IanSB** [comment]
@ShoresOfNowhere 

Try setting the output resolution to 1920x1080 and refresh to only 50Hz or only 60Hz as appropriate for your computer. This will produce a video signal with much more standard timing than the default Auto modes.
