### ISSUE TITLE
Colors not right

### ISSUE THREAD

**Issue by manterola** [c0pperdragon/Amiga-Digital-Video#51]
I am having this problem in a A500+ PAL. The colors are off and I have tried all the options in the settings.
I used the Amiga test kit to help me see where the problem is, and I discovered that the red gradient is not correct.
I have attached a couple of screenshots.
Anyone with similar problems?
Any clue will help me.
Thanks!
![capture8](https://user-images.githubusercontent.com/47620620/119033526-4f733b80-b97b-11eb-8ed7-85a25de633e9.png)
![capture9](https://user-images.githubusercontent.com/47620620/119033552-5437ef80-b97b-11eb-8967-f077187bbe6e.png)

**Comment by IanSB** [comment]
Looks like bit 2 of the red channel is not connected so you need to check the soldering of the surface mount component U3 on pins 4 and 17 which are the input and output of red bit 2

**Comment by manterola** [comment]
Thanks...Yes you are right: that red gradient breaks the progression: 0x00, 0x11, 0x22, 0x33, etc. 
After inspection, the problem wasn't located in the daughter board, it was in the RPi0 itself: Pin #32 is grounded.
I removed the pins around the pin #32 and I am still trying to find a bridge. I remember connecting the board on top of the RPi0 in the wrong direction the first time. Do you think that this action affected and burned the GPIO in the pin #32?
Thanks again for this great development

**Comment by IanSB** [comment]
@manterola 
>Do you think that this action affected and burned the GPIO in the pin 32?

It's possible but the only way to be sure would be to try another Pi. It might be worth checking the operating temperature of the Pi (System summary in the info menu) because I have a damaged Pi and that runs much hotter than a normal one (~90C vs ~50C)

BTW are you sure you are checking pin 32 because if you count from the wrong end that pin would be a GND.

**Comment by manterola** [comment]
Thanks @IanSB . The issue was resolved. I could not find any solder bridging the pin 32 to ground. I desoldered the pins, and followed the traces to see what was wrong. Nothing found, and still pin 32 has connectivity to ground. So I got a new RPi0 today, I checked that pin32 was not grounded and soldered the pin header, and it worked perfectly!.
Thanks for helping me diagnosing this problem.
