### ISSUE TITLE
Amiga 500 Rev 6A Video problem

### ISSUE THREAD

**Issue by marcob1971** [c0pperdragon/Amiga-Digital-Video#52]
Hi all,
on my Amiga 500 Rev 6A, normal denise, raspberry Pi Zero W v.1.1 the video appears with incorrect colors and there are also colored bands similar to interference. I've tried different types of setup but nothing change. Any suggestions? Thank you.

![capture7](https://user-images.githubusercontent.com/69398267/122674464-a5830b00-d1d5-11eb-922a-97e570831dba.png)

**Comment by c0pperdragon** [comment]
You either have damaged input pins on your Raspberry Pi, or someone has made a very poor job in soldering the adapter. 
Looking at this image, it seems that the signals B0, B1, B2 and G2 are low all the time and G2 is fluctuating randomly.
You could try to give the ICs on the adapter a very close visual inspection and watch for missing solder or solder bridges.
Trying a different Pi is another option.
