### ISSUE TITLE
Amiga Interlaced mode is off by one line

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/Amiga-Digital-Video#9]
Hi @IanSB

As previously mentioned: When using 1280x1024 output resolution, an interlaced workbench is off by one interlaced line.

![capture8](https://user-images.githubusercontent.com/10912724/93664828-0e382e00-fa72-11ea-8e2c-e56109addfe2.png)

This can also not be fixed by adjusting the vertical offset, because then the picture is too up.
Even if it could be fixed by adjustements, I guess, the non-interlaced picture would be off instead.

For larger output resolutions this effect is basically the same, but there it is not so noticable:

![capture9](https://user-images.githubusercontent.com/10912724/93665040-a97dd300-fa73-11ea-9366-747934475268.png)
![capture10](https://user-images.githubusercontent.com/10912724/93665042-ac78c380-fa73-11ea-9d1d-7474c4d465ed.png)

**Comment by IanSB** [comment]
Can you try this version:

[kernelrpi.zip](https://github.com/c0pperdragon/Amiga-Digital-Video/files/5252708/kernelrpi.zip)

**Comment by c0pperdragon** [comment]
The Interlace mode looks like it has a balanced top and bottom overscan now with 1680x1050 output resolution. I can not switch to 1280x1024, because the single-button mode does no longer work after swapping out the kernel file. Do I have to make any changes to my setup to re-activate this feature?

**Comment by IanSB** [comment]
The way single button mode is selected was changed: Please update to the current release version first then replace the kernel file with the above:
https://github.com/hoglet67/RGBtoHDMI/releases
https://github.com/hoglet67/RGBtoHDMI/releases/download/20200916_6310e8c/RGBtoHDMI_20200916_6310e8c.zip

**Comment by c0pperdragon** [comment]
Interlaced display is perfect now.
![capture3](https://user-images.githubusercontent.com/10912724/93796251-ddefbb80-fc3a-11ea-80ca-479b4dfad466.png)

I have adjusted my configuration to  the "Trailing -ve" sampling option in preparation for the upcomming SuperDenise-adjusted adapter board. If I got everything correct, this configuration should directly work  with it as well. I have also reduced the overscan a bit because the right area was a bit narrower where the Amiga set the last two pixels to black already.
Also when running my Agnus in NTSC mode, the right overscan ends with a strange jagged border. So 712 pixels is now my maximum width that should fit all purposes.
[Amiga.txt](https://github.com/c0pperdragon/Amiga-Digital-Video/files/5256852/Amiga.txt)

**Comment by IanSB** [comment]
>I have adjusted my configuration to the "Trailing -ve" sampling option

Yes, the above kernel has the corrected text for the sampling option.

BTW the menus are a very flickery in interlaced mode because they are only written on alternate fields.
